services:
  # 1. DATABASE
  mongo:
    image: mongo:latest
    container_name: edukasih_mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - app_net
    deploy:
      resources:
        limits:
          memory: 512M

  # 2. BACKEND
  server:
    build: ./server
    container_name: edukasih_server
    restart: always
    env_file: .env
    environment:
      - MONGO_URI=mongodb://mongo:27017/edukasih
      - PORT=5000
    depends_on:
      - mongo
    volumes:
      - uploads_data:/app/uploads
    networks:
      - app_net
    deploy:
      resources:
        limits:
          memory: 512M

  # 3. FRONTEND
  client:
    build: 
      context: ./client
      args:
        - VITE_API_URL=/ 
    container_name: edukasih_client
    restart: always
    networks:
      - app_net
    deploy:
      resources:
        limits:
          memory: 256M

  # 4. NGINX
  nginx:
    image: nginx:alpine
    container_name: edukasih_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - uploads_data:/var/www/uploads
    depends_on:
      - server
      - client
    networks:
      - app_net

  # 5. CERTBOT
  certbot:
    image: certbot/certbot
    container_name: edukasih_certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

volumes:
  mongo_data:
  uploads_data:

networks:
  app_net:
    driver: bridge
