services:
  mongo:
    image: mongo:latest
    container_name: edukasih-mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017" # Opsional: ekspos jika ingin akses DB dari luar
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 1G

  server:
    build: ./server
    container_name: edukasih-server
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongo:27017/edukasih
      - PORT=5000
    volumes:
      - ./server/uploads:/app/uploads
    depends_on:
      - mongo
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 512M

  client:
    build: 
      context: ./client
      args:
        - VITE_API_URL=/ 
    container_name: edukasih-client
    restart: always
    ports:
      - "80:80"
      - "443:443" # Tambahan untuk HTTPS
    depends_on:
      - server
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 256M

  certbot:
    image: certbot/certbot
    container_name: edukasih-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot


volumes:
  mongo_data:
